# Generated by Django 2.2.3 on 2021-10-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_registro', models.IntegerField(choices=[[0, 'CONSULTAS'], [1, 'RECLAMOS'], [2, 'SUGERENCIAS'], [3, 'FELICITACIONES']])),
                ('mensaje', models.TextField()),
                ('avisos', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
